### ISSUE TITLE
Clarify span.serviceName

### ISSUE THREAD

**Issue by codefromthecrypt** [ExpediaDotCom/haystack-idl#31]
I think the service name in haystack is the same as zipkin.localEndpoint.serviceName, but wanted to clarify. For example, if you concat the relevant parts of localEndpoint with serviceName in [zipkin's proto](https://github.com/openzipkin/zipkin-api/blob/master/zipkin.proto), you'd get:

```proto
  // Lower-case label of the node that recorded this span in in the service
  // graph, such as "favstar". Leave absent if unknown.
  //
  // This is a primary label for trace lookup and aggregation, so it should be
 // intuitive and consistent. Many use a name from service discovery.
```

I looked and seems consistent as Tracer in haystack java client's use of service looks exactly like Brave. Can you clarify this is the case?

https://github.com/ExpediaDotCom/haystack-idl/blob/master/proto/span.proto#L30

**Comment by ashishagg** [comment]
Yes, service name in our span's definition is same as zipkin.localEndpoint.serviceName. 
We are yet to add remote service name in our definitions.

**Comment by shreyaa-sharma** [comment]
Closing this as the question has been answered.
