### ISSUE TITLE
[Request] Publish the proto files as a jar to maven central repos

### ISSUE THREAD

**Issue by worldtiki** [ExpediaDotCom/haystack-idl#34]
Having the proto definitions packaged in a jar would be a more convenient way of managing this, instead of having to manually copy these files

**Comment by shreyaa-sharma** [comment]
Tagging @keshavpeswani to help with this.

**Comment by keshavpeswani** [comment]
Hi @worldtiki ,

I don't understand the ask over here. Can you tell your use-case ?
We do have the proto files being compiled in haystack-commons.jar, which can be consumed directly by the haystack-commons.jar
We are also in the process of creating a haystack-idl.jar for the consumers who just want to use the idl and not the additional functionalities given haystack-commons.

Thanks
Keshav

**Comment by ashishagg** [comment]
we now publish a separate jar with only haystack proto compiled classes. 

```xml
<dependency>
            <groupId>com.expedia.www</groupId>
            <artifactId>haystack-idl-java</artifactId>
            <version>[1.0.57,)</version>
</dependency>
```

**Comment by ashishagg** [comment]
Closing this issue now.

**Comment by worldtiki** [comment]
Hi all! Apologies for not replying sooner.

The ask was more about having the just the public proto definitions and nothing else, that is, having a versioned haystack-idl.jar with just the public proto files.

Imo this project (haystack-idl) has a few issues, namely having leaks from several domains (agent, backend and api) and not being packaged as a jar which is the more convenient way to distribute it.

From the perspective of a 3rd party who just cares about the contract to interact with Haystack, ie, the api (public) proto files I feel like the other definitions (agent and backend) do not belong here. It will also lead to further problems down the line, for example, changes to the agent mean that a new version of the entire thing will have to be released, which will lead to confusion whether someone is using the latest version of the api files or not.
The same applies to the haystack commons. It's an even more bloated version of this :/

Regarding the haystack-idl-java, that's cool, but having just the proto files would be nice too :)

**Comment by ashishagg** [comment]
I agree few definitions need to have own lifecycles, so they can be versioned better. For instance, change in span proto def will not impact the storage-backend definitions.
I will open up a issue to clean this up.
